### ISSUE TITLE
Subjects do not load

### ISSUE THREAD

**Issue by axtloss** [Narzgul/HUntis#2]
Trying to filter the available subjects ends up with an API error, causing the subjects list to not load at all.
Error:
```
An error has occured: {message: startDat and endDate are not within a single school year., code: -8507}
```
This seems to also cause the general calendar view to not work properly, as it doesn't let me go further than the 30th May.

**Comment by Narzgul** [comment]
This was already addressed in the getit branch, I committed to that branch by mistake and didn't have the time to merge it into  the master branch.
Actually didn't think anyone would look at the code, or compile it themself. Gonna need to take more care with comments and useful commit messages :D.
